# Site settings
author: Brittany Grebnov
title: Learning the Language
header-img: img/home-bg.png
email: brittanygrebnova@gmail.com
copyright_name: Brittany Grebnov
description: > # this means to ignore newlines until "baseurl:"
  A Developer's Journey from Beginner to Professional
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: BGrebnova
github_username:  brittanygrebnova

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]

theme: jekyll-theme-minimal