# Site settings
title: Learning the Language
header-img: img/home-bg.png
email: brittanygrebnova@gmail.com
copyright_name: brittanygrebnova
description: > # this means to ignore newlines until "baseurl:"
  A Developer's Journey from Beginner to Professional
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  brittanygrebnova
learn_profile: brittanygrebnova
email_username: brittanygrebnova@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
